project_id = "1c-monitor"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[local_smtp]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_manual_linking = true
enable_anonymous_sign_ins = true
email_auth = true

[realtime]
enabled = true

[analytics]
enabled = false

[functions.watcher]
enabled = true
verify_jwt = false
entrypoint = "./functions/watcher/index.ts"
